create table if not exists public.top_crew (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  member_email text not null,
  position integer not null check (position between 1 and 8),
  created_at timestamptz not null default now(),

  constraint top_crew_owner_member_unique
    unique (owner_email, member_email),

  constraint top_crew_owner_position_unique
    unique (owner_email, position)
);

create index if not exists top_crew_owner_email_idx
  on public.top_crew (owner_email);

alter table public.top_crew enable row level security;

drop policy if exists "top crew public read"
  on public.top_crew;

create policy "top crew public read"
  on public.top_crew
  for select
  using (true);

drop policy if exists "top crew owner insert"
  on public.top_crew;

create policy "top crew owner insert"
  on public.top_crew
  for insert
  with check (
    lower(owner_email) =
    lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists "top crew owner update"
  on public.top_crew;

create policy "top crew owner update"
  on public.top_crew
  for update
  using (
    lower(owner_email) =
    lower(coalesce(auth.jwt() ->> 'email', ''))
  )
  with check (
    lower(owner_email) =
    lower(coalesce(auth.jwt() ->> 'email', ''))
  );

drop policy if exists "top crew owner delete"
  on public.top_crew;

create policy "top crew owner delete"
  on public.top_crew
  for delete
  using (
    lower(owner_email) =
    lower(coalesce(auth.jwt() ->> 'email', ''))
  );
