-- UTV LAUNCH POLISH PACK 2 — SOCIAL + STORIES
-- Run once in Supabase SQL Editor. No DO $$ blocks.

alter table if exists public.feed_comments
  add column if not exists parent_comment_id text;

create index if not exists feed_comments_parent_comment_idx
  on public.feed_comments(parent_comment_id);

create table if not exists public.feed_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id text not null,
  user_email text not null,
  reaction text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists feed_comment_reactions_unique
  on public.feed_comment_reactions(comment_id, user_email, reaction);

create index if not exists feed_comment_reactions_comment_idx
  on public.feed_comment_reactions(comment_id);

alter table public.feed_comment_reactions enable row level security;

drop policy if exists "feed_comment_reactions_read" on public.feed_comment_reactions;
create policy "feed_comment_reactions_read"
on public.feed_comment_reactions for select using (true);

drop policy if exists "feed_comment_reactions_insert_own" on public.feed_comment_reactions;
create policy "feed_comment_reactions_insert_own"
on public.feed_comment_reactions for insert to authenticated
with check (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "feed_comment_reactions_delete_own" on public.feed_comment_reactions;
create policy "feed_comment_reactions_delete_own"
on public.feed_comment_reactions for delete to authenticated
using (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

alter table if exists public.stories add column if not exists music_url text;
alter table if exists public.stories add column if not exists music_title text;
alter table if exists public.stories add column if not exists text_overlay jsonb default '[]'::jsonb;
alter table if exists public.stories add column if not exists stickers jsonb default '[]'::jsonb;
alter table if exists public.stories add column if not exists drawing_data text;
alter table if exists public.stories add column if not exists duration_seconds integer;

create table if not exists public.story_comments (
  id bigint generated by default as identity primary key,
  story_id text not null,
  user_email text not null,
  comment text not null,
  parent_comment_id text,
  created_at timestamptz not null default now()
);

create index if not exists story_comments_story_idx
  on public.story_comments(story_id, created_at);
create index if not exists story_comments_parent_idx
  on public.story_comments(parent_comment_id);

alter table public.story_comments enable row level security;

drop policy if exists "story_comments_read" on public.story_comments;
create policy "story_comments_read"
on public.story_comments for select using (true);

drop policy if exists "story_comments_insert_own" on public.story_comments;
create policy "story_comments_insert_own"
on public.story_comments for insert to authenticated
with check (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "story_comments_delete_own" on public.story_comments;
create policy "story_comments_delete_own"
on public.story_comments for delete to authenticated
using (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

create table if not exists public.story_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id text not null,
  user_email text not null,
  reaction text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists story_comment_reactions_unique
  on public.story_comment_reactions(comment_id, user_email, reaction);
create index if not exists story_comment_reactions_comment_idx
  on public.story_comment_reactions(comment_id);

alter table public.story_comment_reactions enable row level security;

drop policy if exists "story_comment_reactions_read" on public.story_comment_reactions;
create policy "story_comment_reactions_read"
on public.story_comment_reactions for select using (true);

drop policy if exists "story_comment_reactions_insert_own" on public.story_comment_reactions;
create policy "story_comment_reactions_insert_own"
on public.story_comment_reactions for insert to authenticated
with check (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "story_comment_reactions_delete_own" on public.story_comment_reactions;
create policy "story_comment_reactions_delete_own"
on public.story_comment_reactions for delete to authenticated
using (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

insert into storage.buckets (id, name, public)
values ('story-music', 'story-music', true)
on conflict (id) do update set public = true;

drop policy if exists "story_music_public_read" on storage.objects;
create policy "story_music_public_read"
on storage.objects for select using (bucket_id = 'story-music');

drop policy if exists "story_music_authenticated_upload" on storage.objects;
create policy "story_music_authenticated_upload"
on storage.objects for insert to authenticated
with check (bucket_id = 'story-music');

drop policy if exists "story_music_owner_delete" on storage.objects;
create policy "story_music_owner_delete"
on storage.objects for delete to authenticated
using (bucket_id = 'story-music' and owner_id = auth.uid()::text);
