create table if not exists public.bookings (
  id bigint generated by default as identity primary key,

  creator_email text not null,
  requester_email text not null,

  user_email text,
  receiver_email text,

  type text not null default 'booking',

  title text,
  service_name text,

  message text,
  description text,

  booking_date date,
  booking_time time,

  location text,
  budget text,

  status text not null default 'pending',
  is_read boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bookings
  add column if not exists creator_email text;

alter table public.bookings
  add column if not exists requester_email text;

alter table public.bookings
  add column if not exists user_email text;

alter table public.bookings
  add column if not exists receiver_email text;

alter table public.bookings
  add column if not exists type text default 'booking';

alter table public.bookings
  add column if not exists title text;

alter table public.bookings
  add column if not exists service_name text;

alter table public.bookings
  add column if not exists message text;

alter table public.bookings
  add column if not exists description text;

alter table public.bookings
  add column if not exists booking_date date;

alter table public.bookings
  add column if not exists booking_time time;

alter table public.bookings
  add column if not exists location text;

alter table public.bookings
  add column if not exists budget text;

alter table public.bookings
  add column if not exists status text default 'pending';

alter table public.bookings
  add column if not exists is_read boolean default false;

alter table public.bookings
  add column if not exists created_at timestamptz default now();

alter table public.bookings
  add column if not exists updated_at timestamptz default now();

create index if not exists bookings_creator_email_idx
  on public.bookings (creator_email);

create index if not exists bookings_requester_email_idx
  on public.bookings (requester_email);

create index if not exists bookings_created_at_idx
  on public.bookings (created_at desc);

alter table public.bookings enable row level security;

drop policy if exists "bookings participants read"
on public.bookings;

create policy "bookings participants read"
on public.bookings
for select
using (
  lower(coalesce(creator_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
  or
  lower(coalesce(requester_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
  or
  lower(coalesce(user_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
  or
  lower(coalesce(receiver_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
);

drop policy if exists "bookings requester insert"
on public.bookings;

create policy "bookings requester insert"
on public.bookings
for insert
with check (
  lower(coalesce(requester_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
  or
  lower(coalesce(user_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
);

drop policy if exists "bookings participants update"
on public.bookings;

create policy "bookings participants update"
on public.bookings
for update
using (
  lower(coalesce(creator_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
  or
  lower(coalesce(requester_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
)
with check (
  lower(coalesce(creator_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
  or
  lower(coalesce(requester_email,'')) =
  lower(coalesce(auth.jwt() ->> 'email',''))
);
